config/routes.rb
# This file is responsible for the mapping of URLs to the controllers
# that will take action and choose what to display.
# This application has a nested structure, with many resources being
# applicable only in the context of a parent resource.

Tasks::Application.routes.draw do |map|

  # Each 'resources' maps create, read, update, and delete routes for
  #   the corresponding controller. We nest for context.

  resources :users do
      get :validate, :on => :collection
  end

  # Groups are a little more complex. They have the same basic
  # structure, but have sub-resources, one of which has special actions
  # for ownership management.
  resources :groups do
    # group_users are accessed at /group/:id/group_users/:join_id
    resources :group_users do
      # create direct addresses for making and removing owners.
      post :promote, :on => :member
      post :demote, :on => :member
    end

    # Within each group, we have projects, which in turn have tasks.
    resources :projects do
      resources :tasks do 
        resources :comments
      end
    end
  end

  # A user's login, or session, is represented as a singleton resource.
  # GET /new for login form, POST to /create to login, and DESTROY to logout.
  resource :user_session

  # A user first coming to the site (/) will see the projects listing.
  root :to => "groups#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications:
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/group_user.rb
# This class is the bridge between users and groups.
# Aside from a group_id and a user_id, there is one attribute:
# is_admin which is true for site administrators.
class GroupUser < ActiveRecord::Base
  # Associate with the two models we're joining.
  belongs_to :group
  belongs_to :user

  # Make sure we don't wind up with the same user in a group twice
  # (this is needless and might cause funny output)
  validates_uniqueness_of :user_id, :scope => :group_id,
    :message => "is already in that group"
end

app/controllers/group_users_controller.rb
class GroupUsersController < ApplicationController
  # All operations on a GroupUser relationship object are done in
  # the context of a group, and namespaced to /group/:id/

  # Private methods defined at bottom:
  # get_group (finds the current group, provides @group, @parent
  # form_prep (gets some data needed to display the form

  # Before anything, figure out the @group from the URL parameters
  before_filter :get_group

  # GET /group_users
  # GET /group_users.xml
  def index
    @group_users = @parent.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @group_users }
    end
  end

  # GET /group_users/1
  # GET /group_users/1.xml
  def show
    @group_user = @parent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @group_user }
    end
  end

  # GET /group_users/new
  # GET /group_users/new.xml
  def new
    # Make the blank group_user a member of this group (via @parent)
    @group_user = @parent.new
    
    if !current_user or (!current_user.is_admin and !@group.owners.include?(current_user))
       redirect_to @group, :notice => "You cannot add users to that group."
       return
    end

    form_prep #the view will need the listing of @users

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @group_user }
    end
  end

  # GET /group_users/1/edit
  def edit
    @group_user = @parent.find(params[:id])
    form_prep # get the @users for the drop-down
  end

  # POST /group_users
  # POST /group_users.xml
  def create
    # Create the new user, given the params, but already a member of the group
    @group_user = @parent.new(params[:group_user])

    if !current_user or (!current_user.is_admin and !@group.owners.include?(current_user))
       redirect_to @group, :notice => "You cannot add users to that group."
       return
    end

    respond_to do |format|
      if @group_user.save
        format.html { redirect_to(@group, :notice => 'Group user was successfully created.') }
        format.xml  { render :xml => @group_user, :status => :created, :location => @group_user }
      else
        format.html { form_prep and render :action => "new" }
        format.xml  { render :xml => @group_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # POST /group_users/1/promote
  # POST /group_users/1/promote.xml
  # Promote the user to become an owner of the group.
  def promote
    @group_user = @parent.find(params[:id]) #get the record

    if !current_user or (!current_user.is_admin and !@group.owners.include?(current_user))
       redirect_to @group, :notice => "You cannot update users in that group."
       return
    end

    respond_to do |format|
      # We'll set is_owner to true. Remember update_attribute bypasses validations!
      if @group_user.update_attribute(:is_owner, true)
        format.html { redirect_to(@group, :notice => 'Group user was successfully promoted!') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @group_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # POST /group_users/1/demote
  # POST /group_users/1/demote.xml
  # Demote the user to be a non-owner for the group.
  def demote
    @group_user = @parent.find(params[:id]) #get the record

    if !current_user or (!current_user.is_admin and !@group.owners.include?(current_user)) or current_user == @group_user.user
       redirect_to @group, :notice => "You cannot demote that user."
       return
    end

    respond_to do |format|
      # We'll set is_owner to true. Remember update_attribute bypasses validations!
      if @group_user.update_attribute(:is_owner, false)
        format.html { redirect_to(@group, :notice => 'Group user is now a regulare member.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @group_user.errors, :status => :unprocessable_entity }
      end
    end
  end



  # PUT /group_users/1
  # PUT /group_users/1.xml
  def update
    @group_user = @parent.find(params[:id]) #get the record

    respond_to do |format|
      if @group_user.update_attributes(params[:group_user])
        format.html { redirect_to(@group, :notice => 'Group user was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @group_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /group_users/1
  # DELETE /group_users/1.xml
  def destroy
    @group_user = @parent.find(params[:id])
    @user = @group_user.user
    if !current_user or (!current_user.is_admin and !@group.users.include?(current_user))
       redirect_to @group, :notice => "You cannot remove users from that group."
       return
    end
    if @group_user.is_owner
       redirect_to @group, :notice => "You cannot remove an owner from a group."
       return
    end
    if (!current_user.is_admin and !@group.owners.include?(current_user)) and @user != current_user
       redirect_to @group, :notice => "You cannot remove that user from this group."
       return
    end
    
    @group_user.destroy

    respond_to do |format|
      format.html { redirect_to(@group) }
      format.xml  { head :ok }
    end
  end

  private

  # Figure out the current group, provide @group and @parent
  def get_group
    @group = Group.find(params[:group_id])
    @parent = @group.group_users
  end

  # Get info for the form.
  def form_prep
    @users = User.all
  end
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/views/group_users/_form.html.erb
<%= form_for([@group,@group_user]) do |f| %>
  <% if @group_user.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@group_user.errors.count, "error") %> prohibited this group_user from being saved:</h2>
    <ul>
    <% @group_user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.collection_select(:user_id, @users, :id, :alphaname, :include_blank => '') %>
  </div>
  <div class="field">
    <%= f.label :is_owner %><br />
    <%= f.check_box :is_owner %>
  </div>
  <div class="actions">
    <%= f.submit 'Add to Group' %>
  </div>
<% end %>

app/views/group_users/edit.html.erb
<h1>Editing group_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @group_user %> |
<%= link_to 'Back', group_users_path %>

app/views/group_users/index.html.erb
<h1>Listing group_users</h1>

<table>
  <tr>
    <th>Group</th>
    <th>User</th>
    <th>Owner?</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @group_users.each do |group_user| %>
  <tr>
    <td><%= group_user.group %></td>
    <td><%= group_user.user %></td>
    <td><%= group_user.is_owner %></td>
    <td><%= link_to 'Show',[@group, group_user] %></td>
    <td><%= link_to 'Edit', edit_group_group_user_path(@group, group_user) %></td>
    <td><%= link_to 'Destroy', [@group, group_user], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Group user', new_group_group_user_path %>

app/views/group_users/new.html.erb
<h1>New User for <%= link_to @group.name, @group %></h1>

<%= render 'form' %>

<%= link_to 'Back', group_path(@group) %>

app/views/group_users/show.html.erb
<p>
  <b>Group:</b>
  <%= @group_user.group %>
</p>

<p>
  <b>User:</b>
  <%= @group_user.user %>
</p>

<p>
  <b>Is Owner:</b>
  <%= @group_user.is_owner %>
</p>


<%= link_to 'Edit', edit_group_group_user_path(@group, @group_user) %> |
<%= link_to 'Back', group_group_users_path %>