config/routes.rb
# This file is responsible for the mapping of URLs to the controllers
# that will take action and choose what to display.
# This application has a nested structure, with many resources being
# applicable only in the context of a parent resource.

Tasks::Application.routes.draw do |map|

  # Each 'resources' maps create, read, update, and delete routes for
  #   the corresponding controller. We nest for context.

  resources :users do
      get :validate, :on => :collection
  end

  # Groups are a little more complex. They have the same basic
  # structure, but have sub-resources, one of which has special actions
  # for ownership management.
  resources :groups do
    # group_users are accessed at /group/:id/group_users/:join_id
    resources :group_users do
      # create direct addresses for making and removing owners.
      post :promote, :on => :member
      post :demote, :on => :member
    end

    # Within each group, we have projects, which in turn have tasks.
    resources :projects do
      resources :tasks do 
        resources :comments
      end
    end
  end

  # A user's login, or session, is represented as a singleton resource.
  # GET /new for login form, POST to /create to login, and DESTROY to logout.
  resource :user_session

  # A user first coming to the site (/) will see the projects listing.
  root :to => "groups#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications:
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/task.rb
class Task < ActiveRecord::Base
	# Each task is associated with one project and is submitted by one
	# user. The user, however, can be nil, representing a task created
	# by an anonymous user.
	belongs_to :project, :touch => true
	belongs_to :submitter, :class_name => "User"
        # Each task may have a user.
        belongs_to :user
	# Each task can have an unlimited number of comments.
        # These comments are deleted when the task is.
	has_many :comments, :dependent => :destroy
	# Each task must belong to a project.
	validates :project_id, :presence => true
	# The status must be one of:
	# -1 : Invalid
	#  0 : Unverified
	#  1 : Accepted
	#  2 : In Progress
	#  3 : Done
	validates :status_id, :numericality => { :only_integer => true, :greater_than_or_equal_to => -1, :less_than_or_equal_to => 3 }

	# Constant dictionary indicating the human-readable definitions of 
	# the five different statuses.
	Statuses = {-1 => "Invalid", 0 => "Unverified", 1 => "Done", 2 => "In Progress", 3 => "Accepted" }

  # convient method to access the array externally (for forms).
  def statuses
    Statuses
  end

	# Retrieves the human-readable definition of this task's status.
	def status (status = nil)
		return Statuses[self.status_id]
	end
	# Sets the status of this task based on the given human-readable
	# definition.
	def status= (status)
		raise IndexError, "Invalid status" unless Statuses.has_value?(status)
		self.status_id = Statuses.index(status)
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # Anything to do with a project is done in the context of a group.
  # First thing to do is to fetch the @group and @project
  before_filter :get_project

  # Figure out the current group based on the url. This will be provided
  # as @group, and the collection of projects will be @parent.
  def get_project
    @group = Group.find(params[:group_id])
    @project = Project.find(params[:project_id])
    @parent = @project.tasks
  end

  # GET /tasks
  # GET /tasks.xml
  # Retrieves a list of the system's tasks.
  def index
    @tasks = @parent.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.xml
  # Displays the details of the given task.
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.xml
  # Shows a form to create a new task.
  def new
    @task = @parent.new

    # Mark the user. If not an admin, this will be overwritten in create.
    # For admins, they will be themselves by default but get to pick someone else.
    @task.submitter = current_user

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/1/edit
  # Shows a form to edit the given task.
  def edit
    @task = @parent.find(params[:id])
    # Only allow administrators and group members to edit tasks.
    # Return others to the task page.
    if !@task.project.group.users.include?(current_user) and !current_user.is_admin
        respond_to do |format|
            format.html { redirect_to(@task, :notice => "You need to be a member of this group to do that.") }
            format.xml { render :status => :unprocessable_entity }
        end
        return
    end
  end

  # POST /tasks
  # POST /tasks.xml
  # Receives the form data from the new form.
  def create
    @task = @parent.new(params[:task])

    # Set submitter
    if(!current_user.is_admin)
      @task.submitter=current_user
    end

    # Set status if nesc.
    if(!current_user.is_admin && !@task.project.group.owners.include?(current_user))
      @task.status='Unverified'
    end

    # Only allow administrators and group members to create tasks.
    # Return others to the task page.
    if !@task.project.group.users.include?(current_user) and !current_user.is_admin
        respond_to do |format|
            format.html { redirect_to(@task.project, :notice => "You need to be a member of this group to do that.") }
            format.xml { render :status => :unprocessable_entity }
        end
        return
    end

    respond_to do |format|
      if @task.save
        #alert the assignee, if there is one and it has an email
        sent = ""
        unless @task.user.nil? or @task.user.email.nil?
          UserMailer.deliver_new_task(@task, mailer_data)
          sent = ", and the assignee has been notified"
	end

        format.html { redirect_to([@group, @project], :notice => 'Task was successfully created' + sent +'.') }
        format.xml  { render :xml => @task, :status => :created, :location => @task }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.xml
  # Receives the output from the edit form. Updates the task
  # with new data.
  def update
    @task = @parent.find(params[:id])

    respond_to do |format|
      # Only group members and administrators can modify tasks.
      # Return others to the task page.
      if !@task.project.group.users.include?(current_user) and !current_user.is_admin
        format.html { redirect_to([@group, @project], :notice => "You need to be a member of this group to do that.") }
        format.xml { render :status => :unprocessable_entity }
      elsif @task.update_attributes(params[:task])
        #alert the assignee, if there is one and it has an email
        sent = ""
        unless @task.user.nil? or @task.user.email.nil?
          UserMailer.deliver_updated_task(@task, mailer_data)
          sent = ", and the assignee has been notified"
	end

        format.html { redirect_to([@group, @project, @task], :notice => "Task was successfully updated#{sent}.") }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.xml
  # Attempts to delete the given task from the database.
  def destroy
    @task = Task.find(params[:id])
    # Only administrators can completely delete tasks.
    if !current_user or !current_user.is_admin
        respond_to do |format|
            format.html { redirect_to([@group, @project], :notice => "You don't have permission to do that.") }
            format.xml { render :status => :unprocessable_entity }
        end
        return
    end
    @task.destroy

    respond_to do |format|
      format.html { redirect_to([@group, @project], :notice => "Task destroyed.") }
      format.xml  { head :ok }
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for([@group, @project, @task]) do |f| %>
  <% if @task.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
    <ul>
    <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <% if current_user.is_admin %>
  <div class="field">
    <%= f.label :submitter_id %><br />
    <%= f.collection_select(:submitter_id, User.all, :id, :alphaname, :include_blank => '') %>
  </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <% if @task.project.group.owners.include?(current_user) or current_user.is_admin %>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select(:status, @task.statuses.values) %>
  </div>
  <% end %>
  <div class="field">
    <%= f.label :assigned_to %><br />
    <%= f.collection_select(:user_id, @group.users, :id, :alphaname, :include_blank => 'None') %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Project</th>
    <th>Submitter</th>
    <th>Name</th>
    <th>Body</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.project_id %></td>
    <td><%= task.submitter_id %></td>
    <td><%= task.name %></td>
    <td><%= task.body %></td>
    <td><%= task.status %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task for <%= link_to @project.name, [@group, @project] %></h1>

<%= render 'form' %>

<%= link_to 'Back', group_project_path(@group,@project) %>

app/views/tasks/show.html.erb
<h1>Task: <%= @task.name %></h1>
<p>In project <%= link_to @project.name, group_project_path(@group, @project) %></p>
<p>
  <b>Submitted by:</b>
  <%= @task.submitter.name %>
</p>

<p>
  <b>Assigned to:</b>
  <%= @task.user.nil? ? 'Nobody' : @task.user.name %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>


<p>
  <b>Details:</b> <br />
  <%= @task.body %>
  </p>
  <hr>
  <h2>Comments</h2>
<% if @task.comments.empty? %>
  <em>No comments yet.</em>
<% else %>
  <% @task.comments.each do |c| %>
    <p><b><%= c.user.name %> on <%= c.created_at %>:</b>
    <% if current_user and (c.user == current_user or current_user.is_admin) %>
      <small>(
      <%= link_to 'edit', edit_group_project_task_comment_path(@group, @project, @task, c) %>
      <% if current_user.is_admin %>
        | <%= link_to 'destroy', group_project_task_comment_path(@group, @project, @task, c), :method => :delete %>
      <% end %>)</small>
    <% end %>
    <br />
    <%= raw textilize c.body %>
    <% if c.created_at != c.updated_at %>
      <small>(Last edited on <%= c.updated_at %>)</small>
    <% end %>
    </p><br /> 
  <% end %>
<% end %>
<br/>
<% if current_user %>
  <%= link_to 'Add Comment', new_group_project_task_comment_path(@group, @project, @task) %>
<% end %>
<p>
<%= link_to 'Edit', edit_group_project_task_path(@group, @project, @task) %>