config/routes.rb
# This file is responsible for the mapping of URLs to the controllers
# that will take action and choose what to display.
# This application has a nested structure, with many resources being
# applicable only in the context of a parent resource.

Tasks::Application.routes.draw do |map|

  # Each 'resources' maps create, read, update, and delete routes for
  #   the corresponding controller. We nest for context.

  resources :users do
      get :validate, :on => :collection
  end

  # Groups are a little more complex. They have the same basic
  # structure, but have sub-resources, one of which has special actions
  # for ownership management.
  resources :groups do
    # group_users are accessed at /group/:id/group_users/:join_id
    resources :group_users do
      # create direct addresses for making and removing owners.
      post :promote, :on => :member
      post :demote, :on => :member
    end

    # Within each group, we have projects, which in turn have tasks.
    resources :projects do
      resources :tasks do 
        resources :comments
      end
    end
  end

  # A user's login, or session, is represented as a singleton resource.
  # GET /new for login form, POST to /create to login, and DESTROY to logout.
  resource :user_session

  # A user first coming to the site (/) will see the projects listing.
  root :to => "groups#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications:
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :projects # Connects this group to all projects owned by it.
	has_many :active_projects, :class_name => "Project", :conditions => ['active = ?', true]
	has_many :inactive_projects, :class_name => "Project", :conditions => ['active = ?', false]

        # Connect to users, through the group_users model.
        has_many :group_users
        has_many :users, :through => :group_users

        # Some users are owners with special priveleges.
        has_many :owners, :through => :group_users, :source => :user, :conditions => ['is_owner = ?', true]

        # Order alphabetically by default.
        default_scope :order => 'name'
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.xml
  # Displays an index of all groups in the system.
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.xml
  # Displays the details of a single group given by ID.
  def show
    @group = Group.find(params[:id])

    # Collect users and owners, we'll want to display them.
    @users = @group.users
    @owners = @group.owners

    # Don't need to display an owner as a user, too!
    @users.delete_if { |u| @owners.include? u }

    # We'll also want to display our projects.
    @projects = @group.active_projects
    @inactive_projects = @group.inactive_projects


    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.xml
  # Offers the user a form for creating a new group.
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/1/edit
  # Offers the user a form for modifying a group given by ID.
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.xml
  # Accepts the results of the form created in new and tries
  # to use it to create a new group.
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if !current_user || (!current_user.is_admin)
        format.html { redirect_to(@group, :notice => 'No permissions to create groups.')}
        format.xml { render :xml => @group.errors, :status => :unprocessable_entity }
      elsif @group.save
        format.html { redirect_to(@group, :notice => 'Group was successfully created.') }
        format.xml  { render :xml => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.xml
  # Accepts the results of the form created in edit and tries
  # to use it to modify the given group.
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if !current_user || (!current_user.is_admin && !@group.owners.include?(current_user))
        format.html { redirect_to(@group, :notice => 'No permissions to edit group.')}
        format.xml { render :xml => @group.errors, :status => :unprocessable_entity }

      elsif @group.update_attributes(params[:group])
        format.html { redirect_to(@group, :notice => 'Group was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.xml
  # Attempts to destroy the group given by ID.
  def destroy
    @group = Group.find(params[:id])
    # Only administrators can permanently delete groups.
    # Fail gracefully if the user is not allowed.
    if !current_user or !current_user.is_admin
        respond_to do |format|
            format.html { redirect_to(@group, :notice => "You don't have permission to do that.") }
            format.xml { render :status => :unprocessable_entity }
        end
        return
    end
    if !@group.projects.empty?
        respond_to do |format|
            format.html { redirect_to(@group, :notice => "You can't delete a group that owns projects.") }
            format.xml { render :status => :unprocessable_entity }
        end
        return
    end
    @group.destroy

    respond_to do |format|
      format.html { redirect_to(groups_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  # Links the user to the given group as an owner.
  def make_owner_link(group, user)
    #Find the GroupUser record we'll need to modify.
    group_user = GroupUser.find_by_user_id_and_group_id(user.id, group.id)

    # Create a link. We'll POST to /groups/:group_id/group_users/:id/promote
    link_to 'Make Owner', 
      promote_group_group_user_path(group, group_user),
      :method => :post
  end

  # Links the user to the given group as an ordinary member.
  def make_demote_link(group, user)
    #Find the GroupUser record we'll need to modify.
    group_user = GroupUser.find_by_user_id_and_group_id(user.id, group.id)

    # Create a link. We'll POST to /groups/:group_id/group_users/:id/demote
    link_to 'Make regular member', 
      demote_group_group_user_path(group, group_user),
      :method => :post
  end

  # Unlinks the user from the given group.
  def make_remove_link(group, user)
    #Find the GroupUser record we'll need to modify.
    group_user = GroupUser.find_by_user_id_and_group_id(user.id, group.id)

    link_to "Remove from Group", [group, group_user], :method => :delete
  end
end

app/views/groups/_form.html.erb
<% form_for(@group) do |f| %>
  <%= f.error_messages %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>


<% @groups.each do |group| %>
<h2>
  <%= link_to group.name, group %>
  <% if current_user && (group.owners.include?(current_user) || current_user.is_admin) %>
  <small>( <%= link_to 'edit', edit_group_path(group) %> )</small>
  <% end %>
</h2>
<p><%= group.description %></p>
  <% unless group.active_projects.empty? %>
    <p><strong><%= group.active_projects.count %> Active Projects</strong></p>
    <ul>
      <% group.active_projects.each do |p| %>
        <li><%= link_to p.name,[p.group, p] %></li>
      <% end %>
    </ul>
  <% end %>
  <% if current_user and (current_user.is_admin or group.owners.include?(current_user)) %>
    <% unless group.inactive_projects.empty? %>
      <p><strong><%= group.inactive_projects.count %> Inactive Projects</strong></p>
      <ul>
        <% group.inactive_projects.each do |p| %>
          <li><%= link_to p.name,[p.group, p] %></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
<% end %>

<br />

<% if current_user && current_user.is_admin %>
  <%= link_to 'New group', new_group_path %>
<% end %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<%# Note: we use some helper methods (make_*_link) defined in /app/helpers/groups_helper.rb %>
<% @perms =  current_user && (@group.owners.include?(current_user) || current_user.is_admin) %>
<h1><%= @group.name %></h1>
<% if @perms %>
  <%= link_to 'Edit', edit_group_path(@group) %>
  <% if (@projects.nil? or @projects.empty?) and (@inactive_projects.nil? or @inactive_projects.empty?) %>
   | <%= link_to 'Destroy', @group, :confirm => 'Are you sure?', :method => :delete %>
  <% end %>
<% end %>
<p><%= @group.name %> is a group of users in Flagship Tasks.</p>
<p>
  <%= @group.description %>
</p>

<hr />
<h2>Active Projects</h2>
<% if @projects.nil? || @projects.empty? %>
  <em>This group has no active projects.</em>
<% else %>
  <ul>
  <% @projects.each do |p| %>
    <li><%= link_to p.name, [p.group, p] %></li>
  <% end %>
  </ul>
<% end %>
<% if current_user and (current_user.is_admin or @owners.include?(current_user)) %>
  <h3>Inactive Projects</h3>
  <% if @inactive_projects.nil? || @inactive_projects.empty? %>
    <small><em>This group has no inactive projects.</em></small>
  <% else %>
    <ul>
    <% @inactive_projects.each do |p| %>
      <li><small><%= link_to p.name, [p.group, p] %></small></li>
    <% end %>
    </ul>
  <% end %>
<% end %>
<% if @perms %>
  <p><%= link_to "Add new project", new_group_project_path(@group) %></p>
<% end %>

<hr />
<h2>Membership</h2>
<p>
<% if @owners.nil? || @owners.empty? %>
  <em>This group has no owners.</em>
<% else %>
  <b>Owners (users who control the group):</b>
  <ul>
    <% @owners.each do |u| %>
      <li>
      <%= link_to u.name, u %>
      <% if @perms and u != current_user %>
        (<%= make_demote_link(@group,u) %>)
      <% end %>
      </li>
    <% end %>
  </ul>
<% end %>
</p>

<p>
<% if @users.nil? || @users.empty? %>
  <em>There are no additional users.</em>
<% else %>
  <b>Members:</b>
  <ul>
    <% @users.each do |u| %>
      <li>
      <%= link_to u.name, u %> 
      <% if @perms or u == current_user %>
        (<% if @perms %><%= make_owner_link(@group, u) %> | <% end %><%= make_remove_link(@group,u) %>)
      <% end %>
      </li>
    <% end %>
  </ul>
<% end %>
</p>


<% if @perms %>
  <%= link_to 'Add a member', new_group_group_user_path(@group) %>
<% end %>