config/routes.rb
# This file is responsible for the mapping of URLs to the controllers
# that will take action and choose what to display.
# This application has a nested structure, with many resources being
# applicable only in the context of a parent resource.

Tasks::Application.routes.draw do |map|

  # Each 'resources' maps create, read, update, and delete routes for
  #   the corresponding controller. We nest for context.

  resources :users do
      get :validate, :on => :collection
  end

  # Groups are a little more complex. They have the same basic
  # structure, but have sub-resources, one of which has special actions
  # for ownership management.
  resources :groups do
    # group_users are accessed at /group/:id/group_users/:join_id
    resources :group_users do
      # create direct addresses for making and removing owners.
      post :promote, :on => :member
      post :demote, :on => :member
    end

    # Within each group, we have projects, which in turn have tasks.
    resources :projects do
      resources :tasks do 
        resources :comments
      end
    end
  end

  # A user's login, or session, is represented as a singleton resource.
  # GET /new for login form, POST to /create to login, and DESTROY to logout.
  resource :user_session

  # A user first coming to the site (/) will see the projects listing.
  root :to => "groups#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications:
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :name, :presence => true, :length => { :minimum => 3 } # A project must have a name.
	validates :group_id, :presence => true # A project must belong to a group.
	belongs_to :group # Connects the project to the group that owns it.
	has_many :tasks, :order => 'status_id DESC', :dependent => :destroy # Each project can have an unlimited number of tasks.
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # Anything to do with a project is done in the context of a group.
  # First thing to do is to fetch the @group.
  before_filter :get_group

  # Figure out the current group based on the url. This will be provided
  # as @group, and the collection of projects will be @parent.
  def get_group
    @group = Group.find(params[:group_id])
    @parent = @group.projects
  end
  
  # GET /projects
  # GET /projects.xml
  # Lists all projects in the system.
  def index
    @projects = @parent.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  # Gives the full details for a single project given by ID.
  def show
    @project = @parent.find(params[:id])

    @tasks = @project.tasks

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  # Displays a form for creating a new project to the user.
  def new
    @project = @parent.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  # Displays a form for editing a project to the user.
  def edit
    @project = @parent.find(params[:id])
    # Only the owners of the project's group and administrators
    # can modify projects. Fail gracefully if the user is not allowed.
    if !@project.group.owners.include?(current_user) and !current_user.is_admin
        respond_to do |format|
            format.html { redirect_to(@project, :notice => "You need to be an owner of this group to do that.") }
            format.xml { render :status => :unprocessable_entity }
        end
        return
    end
  end

  # POST /projects
  # POST /projects.xml
  # Accepts the results of the new form to create a new project.
  def create
    @project = @parent.new(params[:project])
    logger.info "OH MY FUCING GOD!!!!" if @project.nil?
    logger.info @project

    # Only group owners and administrators can create projects assigned
    # to that group. Fail gracefully if the user is not allowed.
    respond_to do |format|
      if !@project.group.owners.include?(current_user) and !current_user.is_admin
        format.html { redirect_to(@project.group, :notice => "You need to be an owner of this group to do that.") }
        format.xml { render :status => :unprocessable_entity }
      elsif @project.save
        format.html { redirect_to([@group, @project], :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  # Accepts the results of the edit form and attempts to modify the
  # given project.
  def update
    @project = @parent.find(params[:id])

    respond_to do |format|
      # Only the owners of the project's group and administrators can
      # modify a project. Fail gracefully if the user is not allowed.
      newgroup = @group
      if params[:project][:group_id] and @project.group_id != params[:project][:group_id].to_i
        newgroup = Group.find(params[:project][:group_id].to_i)
        @project.errors.add(:group_id, "can only be changed by admins") unless current_user and current_user.is_admin
      end  
      if !current_user or (!@project.group.owners.include?(current_user) and !current_user.is_admin)
        format.html { redirect_to(@project, :notice => "You need to be an owner of this group to do that.") }
        format.xml { render :status => :unprocessable_entity }
      elsif @project.errors.empty? and @project.update_attributes(params[:project])
        format.html { redirect_to([newgroup, @project], :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  # Attempts to delete a project given by ID.
  def destroy
    @project = Project.find(params[:id])
    # Only administrators can permanently delete projects.
    # Fail gracefully if the user is not allowed.
    if !current_user or !current_user.is_admin
        respond_to do |format|
            format.html { redirect_to([@group, @project], :notice => "You don't have permission to do that.") }
            format.xml { render :status => :unprocessable_entity }
        end
        return
    end
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(group_url(@group)) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for([@group, @project]) do |f| %>
  <% if @project.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <% if current_user and current_user.is_admin %>
    <div class="field">
      <%= f.label :group_id %><br />
      <%= f.collection_select(:group_id, Group.all, :id, :name) %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>
  Editing Project <%= link_to @project.name, [@group, @project] %>
  in <%= link_to @group.name, @group %>
</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Group</th>
    <th>Name</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.group_id %></td>
    <td><%= project.name %></td>
    <td><%= project.active %></td>
    <td><%= link_to 'Show', [project.group, project] %></td>
    <td><%= link_to 'Edit', edit_group_project_path(project.group, project) %></td>
    <td><%= link_to 'Destroy', [project.group, project], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_group_project_path(@group) %>

app/views/projects/new.html.erb
<h1>New project for <%= link_to @group.name, @group %></h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<p>A project managed by <%= link_to @group.name, @group %>
<% unless @project.active %>
  <p><em>This project is currently inactive.</em></p>
<% end %>

<h2>Tasks</h2>
<% if @tasks.nil? || @tasks.empty? %>
  <em>This project has no tasks.</em>
<% else %>
  <ul>
  <% @tasks.each do |t| %>
    <li>
      <%= link_to t.name, [@group, @project, t] %>
      (
      <%= t.status %>
      <% unless t.user.nil? %>
      : <%= link_to t.user.name, t.user %>
      <% end %>
      )
      (
      <% if current_user && (current_user.is_admin || @group.owners.include?(current_user)) %>
        <%= link_to 'edit', edit_group_project_task_path(@group, @project, t) %> 
      <% end %>
      <% if current_user && current_user.is_admin %>
        | <%= link_to 'delete', group_project_task_path(@group, @project, t), :method => :delete %>
      <% end %>
      )
        </li>
  <% end %>
  </ul>
<% end %>
<p>
<% if current_user && (current_user.is_admin || @project.group.users.include?(current_user)) %>
  <%= link_to "Add new task", new_group_project_task_path(@group,@project) %> 
<% end %>
<% if current_user && (current_user.is_admin || @group.owners.include?(current_user)) %>
  | <%= link_to 'Edit Project Info', edit_group_project_path(@group, @project) %>
<% end %>

<% if current_user && current_user.is_admin %>
  | <%= link_to 'Delete Project', group_project_path(@group, @project), :method => :delete, :confirm => "Are you sure you want to delete the project?" %>
<% end %>
</p>